# Setup
title:               Matt Didcoe
tagline:             'An ambulance officer, student and occasional landscape photographer'
description:         ''
url:                 https://mattman.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Matt Didcoe
  url:               https://twitter.com/mattdidcoe
  email:             

# Gems
plugins:
  - jekyll-paginate
  - jemoji

# Custom vars
version:             1.1.0
google_analytics_id: 
